- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  weight: 20
  startingGear: HoPGear
  departments:
  - Command
  icon: "HeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Brig
  - Service
  - Mail
  - Salvage
  - Cargo
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - Detective
  # I mean they'll give themselves the rest of the access levels *anyways*.

- type: startingGear
  id: HoPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatHopcap
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
