- type: job
  id: Quartermaster
  name: "quartermaster"
<<<<<<< HEAD
=======
  weight: 10
>>>>>>> 320997bffa49f308ef3e98c08a429cf47eb2666a
  startingGear: QuartermasterGear
  departments:
  - Cargo
  icon: "QuarterMaster"
  supervisors: "the head of personnel"
<<<<<<< HEAD
=======
  canBeAntag: false
>>>>>>> 320997bffa49f308ef3e98c08a429cf47eb2666a
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetCargo
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
