- type: job
  id: SalvageSpecialist
  name: "salvage technician"
  icon: "ShaftMiner"
  startingGear: SalvageSpecialistGear
  departments:
  - Engineering
  supervisors: "the chief engineer"
  access:
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvagePDA
    ears: ClothingHeadsetEngineering
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
