- type: job
  id: Cyborg
  name: "cyborg"
  departments:
  - Engineering
  icon: "Unknown"
  supervisors: "all humans"
  canBeAntag: false
  jobEntity: PlayerCyborgBase
  startingGear: CyborgGear # for char preview only

- type: startingGear
  id: CyborgGear
  equipment:
    head: ClothingHeadHatCardborg
    outerClothing: ClothingOuterCardborg

