- type: job
  id: Assistant
  name: "assistant"
  startingGear: AssistantGear
  departments:
  - Civilian
  icon: "Assistant"
  supervisors: "absolutely everyone"
  access:
  - Maintenance

- type: startingGear
  id: AssistantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatFedoraGrey
    id: AssistantPDA
    ears: ClothingHeadsetSecurity
  innerclothingskirt: ClothingUniformJumpskirtDetectiveGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
