- type: job
  id: Librarian
  name: "cataloguer"
  startingGear: LibrarianGear
  departments:
  - Epistemics
  icon: "Librarian"
  supervisors: "the head of personnel"
  access:
  - Service

- type: startingGear
  id: LibrarianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpackBriefcaseFilled
    shoes: ClothingShoesColorBlack
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d10Dice
  innerclothingskirt: ClothingUniformJumpskirtColorLightBrown
