- type: job
  id: ResearchDirector
<<<<<<< HEAD
  name: "mystagogue"
=======
  name: "research director"
>>>>>>> 320997bffa49f308ef3e98c08a429cf47eb2666a
  weight: 10
  startingGear: ResearchDirectorGear
  departments:
  - Command
  - Epistemics
  icon: "ResearchDirector"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHoodMystic
    outerClothing: ClothingOuterRobeMystic
    id: RnDPDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtColorWhite
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
